# Repository
repo_name: InfosecHouse/InfosecHouse
repo_url: https://github.com/InfosecHouse/InfosecHouse

# Copyright
copyright: Copyright &copy; 2021 - 2023 Infosec House

site_name: Infosec House™
theme:
  name: material
  homepage: https://infosec.house
  site_author: Infosec House
  site_description: >-
    Tools & Resources for Cyber Security Operations.
  font:
    text: Roboto
  logo: assets/logo.png
  favicon: assets/logo.png
  custom_dir: docs/overrides

# Color Theme
  palette:
    - scheme: hackermode

# Repository
  repo_name: infosechouse/infosechouse
  repo_url: https://github.com/infosechouse/infosechouse

# Features
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest  
    - content.code.select
    - content.action.edit
    - content.action.view

# Extras
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/infosechouse
    - icon: fontawesome/brands/github 
      link: https://github.com/infosechouse
    - icon: fontawesome/brands/telegram
      link: https://t.me/infosechouse
    - icon: fontawesome/brands/instagram 
      link: https://instagram.com/infosechouse
  generator: false

# CSS
extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang: en
  - blog:
      enabled: true
      archive: false
      post_date_format: long
      post_url_format: "{slug}"

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html

# Page tree
nav:
  - Home: index.md
  - Offensive Security:
    - API: offensive-security/api.md
    - Blogs: offensive-security/blogs.md
    - Bug Bounty: offensive-security/bug-bounty.md
    - C2: offensive-security/C2.md
    - Cheat Sheets: offensive-security/cheat-sheets.md
    - Cloud: offensive-security/cloud.md
    - Collaboration: offensive-security/collab.md
    - Courses: offensive-security/courses.md
    - Cracking: offensive-security/cracking.md
    - Cryptography: offensive-security/cryptography.md
    - CTF: offensive-security/ctf.md
    - Data Exfiltration: offensive-security/data-exfiltration.md
    - E-Mail: offensive-security/e-mail.md
    - Evasion: offensive-security/evasion.md
    - Exploits: offensive-security/exploits.md
    - Firewalls: offensive-security/firewalls.md
    - Hardware: offensive-security/hardware.md
    - Linux: offensive-security/linux.md
    - Mobile: offensive-security/mobile.md
    - Network: offensive-security/network.md
    - Operating Systems: offensive-security/operating-systems.md
    - Recon: offensive-security/recon.md
    - Shells: offensive-security/shells.md
    - Social Engineering: offensive-security/social-engineering.md
    - Vulnerability Scanners: offensive-security/vuln-scanners.md
    - Web Application: offensive-security/web-app.md
    - Windows: offensive-security/windows.md
    - Wireless: offensive-security/wireless.md
  - Defensive Security:
    - Assets Management: defensive-security/assets-management.md
    - Auditing: defensive-security/auditing.md
    - Cheat Sheets: defensive-security/cheat-sheets.md
    - Courses: defensive-security/courses.md
    - Endpoint Protection: defensive-security/endpoint-protection.md
    - Firewalls: defensive-security/firewalls.md
    - Forensics: defensive-security/forensics.md
    - Honeypot: defensive-security/honeypot.md
    - IDS/IPS: defensive-security/ids-ips.md
    - Indicators of Compromise: defensive-security/ioc.md
    - Incident Response: defensive-security/ir.md
    - Malware: defensive-security/malware.md
    - Mobile: defensive-security/mobile.md
    - Monitoring: defensive-security/monitoring.md
    - Operating Systems: defensive-security/operating-systems.md
    - Phishing: defensive-security/phishing.md
    - Threat Intel: defensive-security/threat-intel.md
  - Operation Security:
    - Anonymity: operation-security/anonymity.md
    - Anti-Forensics: operation-security/antiforensic.md
    - Burners: operation-security/burners.md
    - Communication: operation-security/communication.md
    - Operating Systems: operation-security/operating-systems.md
    - Password & Access Management: operation-security/pass-access-management.md
    - Search Engines: operation-security/search-engines.md
  - Purple Security:
    - Analysis: purple-security/analysis.md
    - Courses: purple-security/courses.md
    - Default Passwords: purple-security/default-passwords.md
    - Editor & Viewers: purple-security/editor-viewer.md
    - Emulation: purple-security/emulation.md
    - Network: purple-security/network.md
    - OSINT: purple-security/osint.md
    - Reverse Engineering: purple-security/re.md
    - Write-Ups: purple-security/write-ups.md
  - Entertainment:
    - Music: entertainment/music.md
    - Videos: entertainment/videos.md
  - Blog:
    - blog/index.md
  - Changelog:
    - changelog/index.md
  - 🤙🏼:
    - thanks.md