name: ReType Github Pages Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: retypeapp/action-build@latest
        env:
        RETYPE_KEY: ${{ secrets.RETYPE_KEY }}
        RETYPE_PASSWORD: ${{ secrets.RETYPE_PASSWORD }}

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true